# Generated by Django 5.2.5 on 2025-08-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('management', 'Management'), ('hod', 'Head of Department'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20),
        ),
    ]
