# Generated by Django 5.2.5 on 2025-08-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('department', 'semester')},
        ),
    ]
