services:
  - type: web
    name: college-portal
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn college_portal.wsgi:application --bind 0.0.0.0:$PORT"
    postDeployCommand: |
      python manage.py migrate
      python manage.py collectstatic --noinput
      echo "import os; from django.contrib.auth import get_user_model; \
      User = get_user_model(); \
      User.objects.create_superuser(os.environ['DJANGO_SUPERUSER_USERNAME'], \
      os.environ['DJANGO_SUPERUSER_EMAIL'], \
      os.environ['DJANGO_SUPERUSER_PASSWORD']) if not User.objects.filter(username=os.environ['DJANGO_SUPERUSER_USERNAME']).exists() else None" \
        | python manage.py shell
      
