services:
  - type: web
    name: college-portal
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn college_portal.wsgi:application --bind 0.0.0.0:$PORT"
    postDeployCommand: |
      python manage.py migrate
      python manage.py collectstatic --noinput
      python manage.py shell < superuser.py
