# Generated by Django 5.2.5 on 2025-09-03 08:58

import college_portal.storage_backends
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, storage=college_portal.storage_backends.MediaStorage(), upload_to='hod_profiles/')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('qualification', models.CharField(blank=True, help_text='Highest qualification (e.g., Ph.D in Electronics)', max_length=200, null=True)),
                ('experience_years', models.PositiveIntegerField(blank=True, help_text='Total years of experience', null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, help_text='Area of expertise', max_length=200, null=True)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, help_text='Brief professional description', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hod_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Head of Department',
                'verbose_name_plural': 'Heads of Department',
            },
        ),
    ]
