# Generated by Django 5.2.5 on 2025-08-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Order Request Sent'), ('DELIVERY_DAY', 'Delivery Day Assigned'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20),
        ),
    ]
