# Generated by Django 5.2.5 on 2025-09-03 08:30

import college_portal.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_image',
            field=models.ImageField(blank=True, null=True, storage=college_portal.storage_backends.MediaStorage(), upload_to='shop/products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=college_portal.storage_backends.MediaStorage(), upload_to='shop/products/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, storage=college_portal.storage_backends.MediaStorage(), upload_to='shop/qr/'),
        ),
    ]
