# Generated by Django 5.2.5 on 2025-09-03 08:30

import college_portal.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=college_portal.storage_backends.MediaStorage(), upload_to='student_profiles/'),
        ),
    ]
