# Generated by Django 5.2.5 on 2025-08-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubchat',
            name='is_poll',
            field=models.BooleanField(default=False),
        ),
    ]
