# Generated by Django 5.2.5 on 2025-09-03 08:30

import college_portal.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(storage=college_portal.storage_backends.MediaStorage(), upload_to='assignments/submissions/'),
        ),
    ]
